### PR TITLE
all: Update go version to 1.6.3

### PR DESCRIPTION
**Pull request by zchee**
First of all, Thanks published great tools!

I found typo(?) in `README.md`. Sorry for nitpicking.
But, `1.6.2` has a security issue(I thought you know, just in case), so I updated it.

and, `runtime/Dockerfile` has wrong file path.
I think it's desirable to manage for each version, therefore small fixed.

If you don't like it, please ignore it.
Thanks.

### CODE REVIEW

**Comment by divan** [comment]
Oh, you're right! I switched from 1.6.2 to 1.6.3 in the last moment. Thanks!

**Comment by zchee** [comment]
@divan Thanks quickly!
but I'm mistake, this PR has unnecessary new line in end of README :(
Sorry, could you remove it?

and, gotrace(actually, output trace patch) does not works use `gb`. When `gb build`, does not proceed.
Now I trying another hack way, but do you have any idea?

**Comment by divan** [comment]
@zchee I'll remove the line.

Regarding the gb, please open new issue if you think it should work. I'll take a look.

**Comment by zchee** [comment]
@divan Thanks!

> Regarding the gb, please open new issue if you think it should work. I'll take a look.

OK.
I was tried only my project. will try simple gb project such as `gsftp`, and post issue if still does not work.

**Pull request merged**
